name: Build Kernel

on:
  workflow_dispatch:

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          VARIANTS=("\"KernelSU\"" "\"SukiSU\"")
          echo "matrix={\"kernelsu_variant\": [$(IFS=,; echo "${VARIANTS[*]}")]}" >> $GITHUB_OUTPUT

  build-kernel:
    runs-on: ubuntu-latest
    needs: set-matrix
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}

    steps:
      - name: Maximize Build Space
        uses: AdityaGarg8/remove-unwanted-software@master
        with:
          remove-dotnet: "true" # Frees ~2 GB
          remove-android: "true" # Frees ~9 GB
          remove-haskell: "true" # Frees ~5.2 GB
          remove-codeql: "true" # Frees ~5.4 GB
          remove-docker-images: "true" # Frees ~3.2 GB
          remove-large-packages: "true" # Frees ~3.1 GB
          remove-swapfile: "true" # Frees ~4 GB
          remove-cached-tools: "false" # Avoid unless confirmed safe

      - name: Checkout
        uses: actions/checkout@main
        with:
          lfs: false

      - name: Install Packages
        run: sudo apt update -y && sudo apt install -y repo

      - name: Initialize and Sync Kernel Source
        run: |
          repo init -u https://android.googlesource.com/kernel/manifest -b common-android13-5.15
          mkdir -p .repo/local_manifests && cp manifests/kernel.xml .repo/local_manifests/default.xml
          repo --trace sync -c -j$(nproc --all) --no-tags --fail-fast

      - name: Add KernelSU
        run: |
          cd sm7550
          case "${{ matrix.kernelsu_variant }}" in
            "KernelSU")
              curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
            ;;
            "SukiSU")
              curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main
            ;;
          esac

      - name: Apply SUSFS Patches
        run: |
          cd sm7550
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android13-5.15
          cp susfs4ksu/kernel_patches/fs/* fs
          cp susfs4ksu/kernel_patches/include/linux/* include/linux

          case "${{ matrix.kernelsu_variant }}" in
            "KernelSU")
              cd KernelSU
              patch -p1 < ../susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch
              cd ..
            ;;
            "SukiSU")
              ls
            ;;
          esac

          patch -p1 < susfs4ksu/kernel_patches/50_add_susfs_in_gki-android13-5.15.patch

      - name: Add Configuration
        run: |
          case "${{ matrix.kernelsu_variant }}" in
            "KernelSU")
              echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=n" >> sm7550/arch/arm64/configs/gki_defconfig
            ;;
            "SukiSU")
              echo "CONFIG_KSU_MANUAL_HOOK=y" >> sm7550/arch/arm64/configs/gki_defconfig
            ;;
          esac

          cat << EOF >> sm7550/arch/arm64/configs/gki_defconfig
          # KernelSU config
          CONFIG_KSU=y
          CONFIG_KSU_SUSFS=y

          # tmpfs config
          CONFIG_TMPFS_XATTR=y
          CONFIG_TMPFS_POSIX_ACL=y

          # Add additional config setting
          CONFIG_IP_NF_TARGET_TTL=y
          CONFIG_IP6_NF_TARGET_HL=y
          CONFIG_IP6_NF_MATCH_HL=y

          # BBR Config
          CONFIG_TCP_CONG_ADVANCED=y
          CONFIG_TCP_CONG_BBR=y
          CONFIG_NET_SCH_FQ=y
          CONFIG_TCP_CONG_BIC=n
          CONFIG_TCP_CONG_WESTWOOD=n
          CONFIG_TCP_CONG_HTCP=n
          EOF

          # Remove check_defconfig
          sed -i 's|check_defconfig||g' sm7550/build.config.gki

      - name: Set Kernel Name
        run: |
          cd sm7550
          sed -i '$s|$res|-EclipseKernel|g' scripts/setlocalversion
          sed -i 's| -dirty||g' scripts/setlocalversion

      - name: Build
        run: |
          LTO=thin BUILD_CONFIG=sm7550/build.config.gki.aarch64 build/build.sh || exit 1
          mkdir artifacts && cd artifacts
          cp ../out/*/dist/Image .

      - name: Make AnyKernel Zip
        run: |
          git clone https://github.com/Kernel-SU/AnyKernel3.git && cd AnyKernel3
          sed -i 's|^kernel\.string=.*|kernel.string=Eclipse Kernel by SomeEmptyBox|' anykernel.sh
          sed -i 's|^do\.devicecheck=.*|do.devicecheck=1|' anykernel.sh
          sed -i 's|^device\.name1=.*|device.name1=eqe|' anykernel.sh
          cp ../out/*/dist/Image .
          zip -r ../artifacts/EclipseKernel-${{ matrix.kernelsu_variant }}.zip .

      - name: Upload Artifacts
        uses: actions/upload-artifact@main
        with:
          name: EclipseKernel-${{ matrix.kernelsu_variant }}
          path: artifacts/*.zip

  Release:
    runs-on: ubuntu-latest
    needs: build-kernel

    steps:
      - name: Checkout Repository
        uses: actions/checkout@main

      - name: Download all artifacts
        uses: actions/download-artifact@main
        with:
          path: artifacts

      - name: Upload artifacts
        run: |
          release=$(date +"%Y-%m-%d")
          gh release create "$release"
          for file in $(find artifacts -type f -name *.zip); do
            echo "Uploading $file..."
            gh release upload "$release" "$file"
          done
        env:
          GH_TOKEN: ${{ github.token }}
