name: Release

on:
  workflow_dispatch:

jobs:
  build_kernel:
    name: Build Kernel
    uses: ./.github/workflows/build_kernel.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - build_kernel

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@main
        with:
          path: artifacts

      - name: Set Release Tag and Notes
        run: |
          echo "release=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
          cat << EOF > release_notes.md

          Eclipse Kernel for Motorola Edge 50 Pro (eqe)

          Features:
          -> KernelSU 1.0.5
          -> SUSFS 1.5.9

          Links:
          -> [KernelSU Manager](https://github.com/tiann/KernelSU/releases/download/v1.0.5/KernelSU_v1.0.5_12081-release.apk)
          -> [SUSFS Module](https://github.com/sidex15/susfs4ksu-module)
          -> [Kernel Flasher](https://github.com/fatalcoder524/KernelFlasher)
          EOF

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Eclipse Kernel
          tag_name: ${{ env.release }}
          body_path: release_notes.md

      - name: Upload Release Assets
        run: |
          for file in $(find artifacts -type f -name *.zip); do
            echo "Uploading $file..."
            gh release upload "${{ env.release }}" "$file"
          done
        env:
          GH_TOKEN: ${{ github.token }}
